name: Spin-up Staging

on:
  workflow_dispatch:
  repository_dispatch:
    types: [plugin-deploy]

jobs:
  spin-up:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
      TF_VAR_duckdns_domain: ${{ secrets.DUCKDNS_DOMAIN }}
      TF_VAR_duckdns_token: ${{ secrets.DUCKDNS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.12.0"
        
      # Terraform Init
      - name: Terraform Init
        run: terraform init

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan -auto-approve
        
      # Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve

      # Get public IP
      - name: Get public IP
        run: |
          PUBLIC_IP=$(terraform output -raw my_ip_public)
          echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV

      # Update DuckDNS
      - name: Update DuckDNS
        run: |
          curl "https://www.duckdns.org/update?domains=${{ secrets.DUCKDNS_DOMAIN }}&token=${{ secrets.DUCKDNS_TOKEN }}&ip=${{ env.PUBLIC_IP }}"

      - name: URL of staging
        run: |
          echo "✅ Staging active at: http://${{ secrets.DUCKDNS_DOMAIN }}.duckdns.org"